Repository MaRDI4NFDI/portal-compose, pull requests merged in 2022-03, with the labels that each got.

#121 add config file for EmbedVideo
  .github/workflows/main.yml
  mediawiki/LocalSettings.d/EmbedVideo.php
Labels: enhancement

#126 Syntax highlight
  mediawiki/LocalSettings.d/LocalSettings.override.php
Labels: enhancement

#136 remove whoami from docker-compose-dev.yml, too, #132 #134
  docker-compose-dev.yml
  traefik/traefik.yml
Labels: bug

#140 tests that extensions and skin are shown in versions page
  test/EmbedVideoTest.py
  test/MedikTest.py
  test/SyntaxHighlightTest.py
Labels: documentation

#156 Traefik readme
  README.md
Labels: documentation

#160 add test for backup metrics, for MaRDI4NFDI/docker-backup#12
  test/test_backup.sh
Labels: enhancement

#161 Update README.md
  README.md
Labels: enhancement

#162 Feature grafana mail
  docker-compose.yml
  grafana/grafana.example.ini
  mediawiki/template.env
  prometheus/prometheus.example.yml
Labels: enhancement
